# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
production:
  daily_ranking:
    class: DailyRankingJob
    schedule: at 5am every day
  linkedin:
    command: LinkedinPublisherJob.perform_later
    schedule: every 60 minutes